spring.application.name=placementportal

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nextgen
spring.datasource.username=postgres
spring.datasource.password=Anya@11
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Run schema.sql on startup (never, as the database tables are already initialized)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Server port
server.port=8080
